# Folder z implemetacja
BASE_DIR = ../../src/3Merge

# # TODO: Pliki wyjsciowe
# OBJ = \
# 	RandomString2/RandomStringTests.o \
# 	Fibonacci1/FibonacciTests.o \
# 	Matrix3/MatrixTests.o

# # TODO: Pliki zrodlowe
# SRC = \
# 	$(BASE_DIR)/RandomString2/RandomStringFunctor.cpp \
# 	$(BASE_DIR)/Fibonacci1/FibonacciFunctor.cpp \
# 	$(BASE_DIR)/Matrix3/Matrix.cpp \
# 	$(BASE_DIR)/Matrix3/MatrixFunctor.cpp \
# 	RandomString2/RandomStringTests.cpp \
# 	Fibonacci1/FibonacciTests.cpp \
# 	Matrix3/MatrixTests.cpp

# Zaladuj flagi kompilacyjne z glownego Makefile'a
include ../../Makefile

# # TODO: Pliki naglowkowe
# HEADERS = \
# 	$(BASE_DIR)/RandomString2/RandomStringFunctor.hpp \
# 	$(BASE_DIR)/Fibonacci1/FibonacciFunctor.hpp \
# 	$(BASE_DIR)/Matrix3/Matrix.hpp \
# 	$(BASE_DIR)/Matrix3/MatrixFunctor.hpp \
# 	RandomString2/RandomStringTests.hpp \
# 	Fibonacci1/FibonacciTests.hpp \
# 	Matrix3/MatrixTests.hpp \
# 	TestFixture.hpp

# kompiluj wszystkie pliki w tym folderze
all: $(OBJ)

# # TODO: Kompilator testow
# RandomString2/RandomStringTests.o: $(HEADERS) RandomString2/RandomStringTests.cpp RandomString2/RandomStringTests.hpp
# 	$(COMPILE) $(CXXFLAGS) -c RandomString2/RandomStringTests.cpp -o RandomString2/RandomStringTests.o

# Fibonacci1/FibonacciTests.o: $(HEADERS) Fibonacci1/FibonacciTests.cpp Fibonacci1/FibonacciTests.hpp
# 	$(COMPILE) $(CXXFLAGS) -c Fibonacci1/FibonacciTests.cpp -o Fibonacci1/FibonacciTests.o

# Matrix3/MatrixTests.o: $(HEADERS) Matrix3/MatrixTests.cpp Matrix3/MatrixTests.hpp
# 	$(COMPILE) $(CXXFLAGS) -c Matrix3/MatrixTests.cpp -o Matrix3/MatrixTests.o

# Inne metody
clean:
	rm -f $(OBJ)

.PHONY: all clean
